apiVersion: coveros.apps.com/v1alpha1
kind: Release
metadata:
  name: jenkins
  namespace: default
spec:
  chart: stable/jenkins
  version: 2.4.1
  wait: false
  maxRetries: 1
  values:
    master:
      adminUser: admin
      adminPassword: admin
    persistence:
      enabled: false
