apiVersion: coveros.apps.com/v1alpha1
kind: HelmRelease
metadata:
  name: kube-ops
  namespace: kube-ops
spec:
  chart: stable/kube-ops-view
  version: 1.2.0
  wait: false
  values:
    ingress:
      enabled: true
      hostname: kube-ops-view.amritgill.ml
