apiVersion: coveros.apps.com/v1alpha1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: prometheus
spec:
  chart: stable/prometheus-operator
  version: 9.1.1 
  wait: false
  values:
    grafana:
      adminPassword: password
