# permissions for end users to view Releases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: Release-viewer-role
rules:
- apiGroups:
  - coveros.apps.com
  resources:
  - Releases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coveros.apps.com
  resources:
  - Releases/status
  verbs:
  - get
