# permissions for end users to edit Releases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: Release-editor-role
rules:
- apiGroups:
  - coveros.apps.com
  resources:
  - Releases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coveros.apps.com
  resources:
  - Releases/status
  verbs:
  - get
