{{- $root := . }}
{{- with .Values.deployments.genoa }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "genoa.fullname" $root }}
  namespace: {{ $root.Release.Namespace }}
  {{- if .labels }}
  labels:
{{ toYaml .labels | indent 4 }}
  {{- end }}
  {{- if .annotations }}
  annotations:
{{ toYaml .annotations | indent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      name: genoa
      {{- if .podLabels }}
{{ toYaml .podLabels | indent 6 }}
      {{- end }}
  replicas: {{ .replicaCount | default 1 }}
  template:
    metadata:
      labels:
        name: genoa
      {{- if .podLabels }}
{{ toYaml .podLabels | indent 8 }}
      {{- end }}
      annotations:
        {{- if .podAnnotations }}
{{ toYaml .podAnnotations | indent 8 }}
        {{- end }}
    spec:
      {{- if .nodeSelector }}
      nodeSelector:
{{ toYaml .nodeSelector | indent 8 }}
      {{- end }}
      serviceAccountName: {{ include "genoa.fullname" $root }}
      volumes:
      - name: additional-helm-repos
        secret:
          secretName: additional-helm-repos
      {{- if .volumes }}
{{ toYaml .volumes | indent 6 }}
      {{- end }}
      {{- if .imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .imagePullSecrets | indent 6 }}
      {{- end }}
      {{- if .initContainers }}
      initContainers:
{{- toYaml .initContainers | indent 6 }}
      {{- end }}
      containers:
      - name: {{ include "genoa.fullname" $root }}
        command:
        - /genoa
        args:
        - --enable-leader-election
        - --custom-helm-repos-file=/tmp/additional-helm-repos-config.yaml
        image: {{ .image.repository }}:{{ .image.tag }}
        imagePullPolicy: {{ .image.pullPolicy }}
        volumeMounts:
        - mountPath: /tmp
          name: additional-helm-repos
        {{- if .volumeMounts }}
{{ toYaml .volumeMounts | indent 8 }}
        {{- end }}
        {{- if .resources }}
        resources:
{{ toYaml .resources | indent 10 }}
        {{- end }}
        {{- if $root.Values.config.notification.enabled }}
        envFrom:
        - secretRef:
            name: notification-secret
        {{- end }}
        {{- if .envVars }}
        env:
{{ toYaml .envVars | indent 8 }}
        {{- end }}
  {{- end }}

