{{- if .Values.config.notification.enabled }}
{{- $root := . }}
{{- with .Values.config.notification }}
apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  namespace: {{ $root.Release.Namespace }}
type: opaque
data:
  NOTIFICATION_PROVIDER: {{ .provider | b64enc }}
  DEFAULT_CHANNEL_ID: {{ .defaultChannelID | b64enc }}
  NOTIFICATION_PROVIDER_TOKEN: {{ .token | b64enc }}
{{- end }}
{{- end }}