apiVersion: v1
kind: Secret
metadata:
  name: {{ include "genoa.fullname" . }}
  namespace:  {{ .Release.Namespace }}
data:
  {{- if .Values.config.github.enabled }}
  {{- with .Values.config.github }}
  GITHUB_WEBHOOK_SECRET: {{ required "github webhook secret is required" .webhookSecret | b64enc }}
  GITHUB_PERSONAL_ACCESS_TOKEN: {{  required "github access token is required" .accessToken | b64enc }}
  GITHUB_DEPLOY_DIRECTORY: {{ .deployDir | b64enc }}
  {{if .selfHostedUrl }}
  GITHUB_ENTERPRISE_HOSTED_URL: {{ .selfHostedUrl | b64enc }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- if .Values.config.gitlab.enabled }}
  {{- with .Values.config.gitlab }}
  GITLAB_WEBHOOK_SECRET: {{ required "gitlab webhook secret is required" .webhookSecret | b64enc }}
  GITLAB_PERSONAL_ACCESS_TOKEN: {{ required "gitlab access token is required" .accessToken | b64enc }}
  GITLAB_DEPLOY_DIRECTORY: {{ .deployDir | b64enc }}
  {{if .selfHostedUrl }}
  GITLAB_SELF_HOSTED_URL: {{ .selfHostedUrl | b64enc }}
  {{- end }}
  {{- end }}
  {{- end }}