apiVersion: v1
kind: Secret
metadata:
  name: {{ include "genoa.fullname" . }}
  namespace:  {{ .Release.Namespace }}
data:
  {{- with .Values.config.github }}
  GITHUB_WEBHOOK_SECRET: {{ .webhookSecret | b64enc }}
  GITHUB_PERSONAL_ACCESS_TOKEN: {{ .accessToken | b64enc }}
  GITHUB_DEPLOY_DIRECTORY: {{ .deployDir | b64enc }}
  {{- end }}
  {{- with .Values.config.gitlab }}
  GITLAB_WEBHOOK_SECRET: {{ .webhookSecret | b64enc }}
  GITLAB_PERSONAL_ACCESS_TOKEN: {{ .accessToken | b64enc }}
  GITLAB_DEPLOY_DIRECTORY: {{ .deployDir | b64enc }}
  {{- end }}