apiVersion: v1
kind: Secret
metadata:
  name: {{ include "genoa.fullname" . }}
  namespace:  {{ .Release.Namespace }}
data:
  WEBHOOK_SECRET: {{ required "A github webhook secret is required" .Values.config.webhookSecret | b64enc }}
  GITHUB_PERSONAL_ACCESS_TOKEN: {{ required "A github personal access token is required" .Values.config.githubPersonalAccessToken | b64enc }}