---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "genoa.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    name: genoa-gitwebhook
    {{- if .Values.deployments.gitWebhook.podLabels }}
{{ toYaml .Values.deployments.gitWebhook.podLabels | indent 4 }}
    {{- end }}
  ports:
  - port: 8081
    targetPort: 8081