## Why cluster-admin -- because helm client inside operator would need freedom to install releases
## TODO: when shifted over to chart, parameterize permissions
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: genoa
subjects:
  - kind: ServiceAccount
    name: genoa
    namespace: genoa
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io