apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: genoa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: genoa
  namespace: genoa
---
apiVersion: v1
data:
  custom-helm-repos-config.yaml: YXBpVmVyc2lvbjogdjEKcmVwb3NpdG9yaWVzOgotIGNhRmlsZTogIiIKICBjZXJ0RmlsZTogIiIKICBrZXlGaWxlOiAiIgogIG5hbWU6IGNvZGV2ZXJvcwogIHBhc3N3b3JkOiAiIgogIHVybDogaHR0cHM6Ly9jb3Zlcm9zLmdpdGh1Yi5pby9jb2RldmVyb3MKICB1c2VybmFtZTogIiI=
kind: Secret
metadata:
  name: custom-helm-repos
  namespace: genoa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: genoa
  namespace: genoa
  labels:
    name: genoa
spec:
  selector:
    matchLabels:
      name: genoa
  replicas: 1
  template:
    metadata:
      labels:
        name: genoa
    spec:
      serviceAccountName: genoa
      volumes:
        - name: custom-helm-repos
          secret:
            secretName: custom-helm-repos
      containers:
        - command:
            - /genoa
          args:
            - --enable-leader-election
            - --custom-helm-repos-file=/tmp/custom-helm-repos-config.yaml
          image: agill17/genoa:0.1.0
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /tmp
              name: custom-helm-repos
          name: genoa
          ports:
            - containerPort: 8081 # for github webhook
          livenessProbe:
            httpGet:
              port: 8081
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
#          resources:
#            limits:
#              cpu: 500m
#              # recommended when running 10 workers.
#              # if running <= 5 workers; then the limit can be 500Mi.
#              # This number can also fluctuate based on the size of chart being installed ( for example, installing 10 prometheus-operators could consume upto 5Gi memory because of helm hooks )
#              memory: 1Gi
#            requests:
#              cpu: 100m
#              memory: 500Mi
          env:
            - name: DEPLOY_DIRECTORY
              value: "sample-helmReleases"
            - name: WEBHOOK_SECRET
              value: "YOUR-WEBHOOK-SECRET-REQUIRED"
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: genoa
  namespace: genoa
spec:
  selector:
    name: genoa
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: genoa
  namespace: genoa
  annotations: {}
spec:
  rules:
  - host: genoa.amritgill.ml
    http:
      paths:
        - path: /webhook
          backend:
            serviceName: genoa
            servicePort: 8081