apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: genoa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: genoa
  namespace: genoa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: genoa
  namespace: genoa
  labels:
    name: genoa
spec:
  selector:
    matchLabels:
      name: genoa
  replicas: 1
  template:
    metadata:
      labels:
        name: genoa
    spec:
      serviceAccountName: genoa
      containers:
        - command:
            - /genoa
          args:
            - --enable-leader-election
          image: agill17/genoa:0.1.0
          imagePullPolicy: Always
          name: genoa
          ports:
            - containerPort: 8081 # for github webhook
          livenessProbe:
            httpGet:
              port: 8081
              path: /health
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 250Mi
          env:
            - name: RELEASE_FILES_DIR
              value: "deploy/minikube"
            - name: WEBHOOK_SECRET
              value: "YOUR-WEBHOOK-SECRET-REQUIRED"
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: genoa
  namespace: genoa
spec:
  selector:
    name: genoa
  ports:
    - port: 8081
      targetPort: 8081
