apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: helm-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-operator
  namespace: helm-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-operator
  namespace: helm-operator
  labels:
    name: helm-operator
spec:
  selector:
    matchLabels:
      name: helm-operator
  replicas: 1
  template:
    metadata:
      labels:
        name: helm-operator
    spec:
      serviceAccountName: helm-operator
      containers:
        - command:
            - /helm-operator
          args:
            - --enable-leader-election
          image: agill17/genoa:0.1.0
          imagePullPolicy: Always
          name: helm-operator
          ports:
            - containerPort: 8081 # for github webhook
          livenessProbe:
            httpGet:
              port: 8081
              path: /health
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 500Mi
          env:
            - name: RELEASE_FILES_DIR
              value: "deploy/minikube"
            - name: WEBHOOK_SECRET
              value: "YOUR-WEBHOOK-SECRET-REQUIRED"
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: helm-operator
  namespace: helm-operator
spec:
  selector:
    name: helm-operator
  ports:
    - port: 8081
      targetPort: 8081
