

#nameOverride: ""
#fullnameOverride: ""

deployments:
  genoa:
    replicaCount: 1
    image:
      repository: agill17/genoa
      pullPolicy: Always
      tag: 0.5.0
    imagePullSecrets: []
    labels: {}
    annotations: {}
    volumes: []
    volumeMounts: []
    podAnnotations: {}
    podLabels: {}
    initContainers: []
    envVars: []
    nodeSelector: {}
    resources: {}
  gitWebhook:
    replicaCount: 1
    image:
      repository: agill17/genoa
      pullPolicy: Always
      tag: 0.5.0
    imagePullSecrets: []
    labels: {}
    annotations: {}
    volumes: []
    volumeMounts: []
    podAnnotations: {}
    podLabels: {}
    initContainers: []
    envVars: []
    nodeSelector: {}
    livenessProbe:
      httpGet:
        port: 8081
        path: /health
      initialDelaySeconds: 10
      periodSeconds: 30
      timeoutSeconds: 10
      successThreshold: 1
      failureThreshold: 3
    resources: {}


config:
  notification:
    #enabled: true
    #provider: "slack"
    #defaultChannelID: ""
    #token: ""
  github:
    #enabled: true
    #deployDir: deploy/
    # you can generate webhookSecret using $ ruby -rsecurerandom -e 'puts SecureRandom.hex(20)'
    # set that value here and also set the same value in your github webhook configuration(s)
    #webhookSecret: ""
    #accessToken: ""
  gitlab: {}
    #enabled: false
    #deployDir: deploy/
    ## you can generate webhookSecret using $ ruby -rsecurerandom -e 'puts SecureRandom.hex(20)'
    ## set that value here and also set the same value in your gitlab webhook configuration(s)
    #webhookSecret: ""
    #accessToken: ""
  helmRepos: |
    apiVersion: v1
    repositories:
    - caFile: ""
      certFile: ""
      keyFile: ""
      name: codeveros
      password: ""
      url: https://coveros.github.io/codeveros
      username: ""
    - caFile: ""
      certFile: ""
      keyFile: ""
      name: choerodon
      password: ""
      url: https://openchart.choerodon.com.cn/choerodon/c7n
      username: ""
    - caFile: ""
      certFile: ""
      keyFile: ""
      name: agill17
      password: ""
      url: https://agill17.github.io/helm-charts
      username: ""

extraConfigMaps: []

## because helm client inside operator would need freedom to install releases
clusterRole: cluster-admin

ingress: {}
  #enabled: false
  #labels: {}
  #annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  #host: genoa.foo.com
  #tls: []
  #hosts: []