

#nameOverride: ""
#fullnameOverride: ""

deployments:
  genoa:
    replicaCount: 1
    image:
      repository: coveros/genoa
      pullPolicy: Always
      tag: 0.6.0
    imagePullSecrets: []
    labels: {}
    annotations: {}
    volumes: []
    volumeMounts: []
    podAnnotations: {}
    podLabels: {}
    initContainers: []
    envVars: []
    nodeSelector: {}
    resources: {}


config:
  notification: {}
    #enabled: true
    #provider: "slack"
    #defaultChannelID: ""
    #token: ""
  helmRepos: |
    apiVersion: v1
    repositories:
    - caFile: ""
      certFile: ""
      keyFile: ""
      name: codeveros
      password: ""
      url: https://coveros.github.io/codeveros
      username: ""
    - caFile: ""
      certFile: ""
      keyFile: ""
      name: choerodon
      password: ""
      url: https://openchart.choerodon.com.cn/choerodon/c7n
      username: ""
    - caFile: ""
      certFile: ""
      keyFile: ""
      name: agill17
      password: ""
      url: https://agill17.github.io/helm-charts
      username: ""

extraConfigMaps: []

## because helm client inside operator would need freedom to install releases
clusterRole: cluster-admin
